<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.5.0-beta1 setup script
 * Date: Sat, 29 Aug 2015 11:14:40 -0300
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'http';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['AllowRoot'] = false;

/* End of servers configuration */

$cfg['blowfish_secret'] = '55e0eee96cf692.38839318';
$cfg['DefaultLang'] = 'pt';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>